### PR TITLE
Support doc values in document tab

### PR DESCRIPTION
**Pull request by mocobeta**
New features to doc values support.

If doc values for fields are available,

- Show doc values data in document tab and pop up window.
- Allow users to copy doc values data to clip board.
- Allow users to save doc values data to local file in the same manner as field data.

**Screen shots**

"Doc Values" column data in document tab:

pivot-luke-docvalues1

Pop up window to show details:

pivot-luke-docvalues2
pivot-luke-docvalues3

Other fixes:

- Update java version to 1.8.0
- Remove norm type from flags (this was removed at Lucene 5)
- Disable add/reconstruct document feature (for now, they are broken and dangerous...)

### CODE REVIEW

**Comment by DmitryKey** [comment]
This looks very exciting @mocobeta! Thanks for taking care of DocValues. Would you like to do the honors and merge this to master as well?

**Comment by mocobeta** [comment]
@DmitryKey Yes, I'll investigate master branch to support doc values as well!

**Comment by DmitryKey** [comment]
thanks @mocobeta ! I have just tested on the solr example index techproducts. DocValues are read and displayed correctly. One visual glitch is in the DocValues dialog:
screen shot 2016-04-02 at 19 50 23

can it be related to the table's column width?

**Comment by mocobeta** [comment]
Thank you for testing, I'll check it soon.

**Comment by mocobeta** [comment]
@DmitryKey Fixed at #54 . Thanks!

**Comment by DmitryKey** [comment]
Thanks for quick fix @mocobeta  !

**Pull request merged**
