### PR TITLE
Upgrade to Lucene 7.2.0

### PR DESCRIPTION
**Pull request by mocobeta**
Updated pom file, fixed to use latest Lucene APIs.

### CODE REVIEW

**Comment by mocobeta** [comment]
@DmitryKey  I plan to make a release luke 7.2.0. Why don't we announce JavaFX version luke as well to get feedback from others?

**Comment by DmitryKey** [comment]
@mocobeta thanks for the PR. In the other thread on JavaFX I suggested to switch branches around, because JavaFX version looks so good! But yes, we could also take the approach of announcing JavaFX for testing and then switch if there are no major issues.

**Comment by mocobeta** [comment]
@DmitryKey Thank you! Either approach is fine to me... But first, let me introduce JavaFX version to all when announcing (thinlet) luke 7.2.0 release. We can switch the branches from next release.
I plan to make a release around January 10th, after returning holidays. :)

**Comment by DmitryKey** [comment]
@mocobeta have a good one :)

**Pull request merged**
