### PR TITLE
Upgrade lucene version 7

### PR DESCRIPTION
**Pull request by mocobeta**
#91 

- Upgrade lucene version 7.0.1
- Use BM25Similarity as default similarity instead of ClassicSimilarity

### CODE REVIEW

**Comment by mocobeta** [comment]
@DmitryKey Seems ok to open/browse/search/optimize Lucene 7 (and 6 for backward compatibility) index. Could you check it?

**Comment by DmitryKey** [comment]
Hey @mocobeta 
Tested with solr 7.0.1 based index and works just fine. Can you release this?
I'll create a ticket for 7.1.0 upgrade.

**Comment by mocobeta** [comment]
@DmitryKey Sure, but can we skip 7.0 release because 7.1 release should work with Lucene 7.0 ??
I'll take time for #94 soon.

**Comment by mocobeta** [comment]
There are no API changes on Lucene 7.1.0, so it is enough just to update pom.xml. 
I'll release this.

**Pull request merged**
