### PR TITLE
Fixed lastAnalyzer retrieval

### PR DESCRIPTION
**Pull request by edegaudenzi**
To make possible again the "Analyzer to use for query parsing" prefilled with last used.

This feature was fully working in preview major release. Since the V4 I noticed that every time I restarted Luke, I always had to reset my analyzer in the combobox. Now it works again, the last used analyzer is correctly retrieved.

### CODE REVIEW

**Comment by DmitryKey** [comment]
thanks for your contribution, @edegaudenzi ! I have verified the feature on ubuntu.

**Comment by edegaudenzi** [comment]
you’re welcome Dmitry! ;)

I can confirm that it works also on MacOS mavericks, Xubuntu 14.04 and Win8.1.

see u soon!

En



Il giorno 20/ago/2015, alle ore 14:41, Dmitry Kan <notifications@github.com> ha scritto:

**Comment by DmitryKey** [comment]
Thanks for additional testing, this is always helpful!

**Comment by edegaudenzi** [comment]
;)

I just created a new pull req (I'll promise, the last one for the moment :) to enable command key on mac to copy-paste etc. 

Tested on MacOS mavericks, lubuntu 14.04, win8.1. (on OS other then Mac, I just checked that everything was still working)

see you soon! ;)

Enrico

**Comment by DmitryKey** [comment]
sounds cool, thanks! I started working on the same issue a while ago, but drowned in other tasks. Thanks! Keep'em coming! :)

**Pull request merged**
