### PR TITLE
Updated Lucene version to 6.3.0

### PR DESCRIPTION
**Pull request by o5k6**
No changes other than to the POM itself.

### CODE REVIEW

**Comment by mocobeta** [comment]
Thank you for the PR.
Lucene 6.3.0 has no API changes, so it would work. (I've not tested yet...)
http://lucene.apache.org/core/6_3_0/changes/Changes.html#v6.3.0.api_changes

**Comment by mocobeta** [comment]
Major functions (browsing, searching, optimizing index) are works well with lucene/solr 6.3.0. 
Merged, thanks!

**Comment by mocobeta** [comment]
@DmitryKey Seems ready for release 6.3.0 ? :-)

**Comment by DmitryKey** [comment]
@mocobeta sure :) feel free to do the honors!

**Comment by mocobeta** [comment]
@DmitryKey I've created a draft release 6.3.0. Could you check it? I'll published the release and announce if it's ok.

**Pull request merged**
