### PR TITLE
#37 Updating to Lucene 5.3

### PR DESCRIPTION
**Pull request by gunnarmorling**
I hope that's all needed to do the update to 5.3. It let's me open an index created by Lucene 5.3, but I am not familiar with the Luke codebase, so I hope I didn't forget anything. Hope it helps.

### CODE REVIEW

**Comment by DmitryKey** [comment]
Thanks for your pr @gunnarmorling ! There is another pr on the same subject. Let me review both and get back to you!

**Comment by lambdaupb** [comment]
Works nicely for me.

**Comment by mocobeta** [comment]
+1 Works fine for me. (can browse terms, search / commit / optimize index, add / delete docs)

**Comment by DmitryKey** [comment]
thanks, guys, I have merged it.

**Pull request merged**
