### PR TITLE
Lucene 5x support

### PR DESCRIPTION
**Pull request by mocobeta**
This is a draft pull request. Comments and reviews are appreciated.
All compiling errors have been resolved, and the build module can browse Lucene 4.x and 5.1 indexes.

Todos:
* Some old codes still remain (commented out) -- should be deleted when they are merged to trunk.
* UIs for "TermInfos index divisor" should be removed -- I think, but not sure...
  * line 53 of luke.xml and line 30 to 33 of lukeinit.xml
* Components other than Lucene should be upgraded?
  * I upgraded only Lucene version to 5.1.0 in pom.xml

Notes:
* Custom classes for Elasticsearch (e.g. org.apache.lucene.analysis.PrefixAnalyzer) does not work because ES 1.5 supports Lucene 4.

Thanks.

### CODE REVIEW

**Comment by DmitryKey** [comment]
@mocobeta thanks for your heroic effort! Major functions work just fine.

So far found that the index optimization throws an NPE:

```
java.lang.NullPointerException
	at org.apache.lucene.index.IndexWriter.isLocked(IndexWriter.java:4352)
	at org.getopt.luke.Luke.openIndex(Luke.java:863)
	at org.getopt.luke.Luke.actionReopen(Luke.java:828)
	at org.getopt.luke.Luke$10.run(Luke.java:2471)
```

**Comment by mocobeta** [comment]
Thanks commnts,

> So far found that the index optimization throws an NPE:

NPEs in "Optimize" and "Re-open index" were fixed in the commit 5bc91a8. This is caused by API change in Directory coustructor, but I did not notice because compile was OK. Similar errors can still remain, I'll check other getConstructor() calls.

**Comment by mocobeta** [comment]
Sorry, I have been away for a while...

I have checked those functions works fine.
* Browse index and documents with Overview / Documents tabs
* Search index with Search tab
* Browse index files with Commits tab
* Re-open / close / optimize index, clean up index directory, check index, export index to XML
* Plugins
  * Analyzer tool, Scripting luke, Custom similarity, Vocablary analysis, Zipf distribution
  * I've not checked HadoopPlugin yet. (It was not modified at all.)

Could we merge that to master? (or maybe better to wait until 5.2 release.)
If you are okay with that, I'm ready to delete all commeted old codes from this branch before merging.

**Comment by DmitryKey** [comment]
Hi,

Been away too. Sure, go ahead and delete the commented out lines. I'll merge it to master and push to release after some more testing.

**Comment by DmitryKey** [comment]
@mocobeta most of the features are worknig fine now with lucene 5.2.0. Is there anything you would like to polish still?

One feature currently failing is the index optimization.

**Comment by mocobeta** [comment]
> Is there anything you would like to polish still?

All obsolete and unused methods / parameters were removed.
Thanks!

In my environment (small data sets,) index optimization seems to work well.
Could you share stack traces? I'll try to produce the failure.

**Comment by DmitryKey** [comment]
Hi Tomoko,

The bug with index optimization appears, if you try to optimize the index
second time in the same session. Here is what I get:

The UI message box: ERROR reopening after optimize:
this IndexReader is closed


trace:

org.apache.lucene.index.IndexNotFoundException: no segments* file found in
MMapDirectory@/home/dmitry/projects/SOLR/solr5/solr-5.2.0/server/solr/core0/data
lockFactory=org.apache.lucene.store.NativeFSLockFactory@4e2ff865: files:
[index, tlog]
        at
org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:655)
        at
org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:612)
        at
org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:442)
        at org.getopt.luke.Luke.openIndex(Luke.java:868)
        at org.getopt.luke.Luke.actionReopen(Luke.java:818)
        at org.getopt.luke.Luke$10.run(Luke.java:2438)


On Mon, Jun 29, 2015 at 6:53 PM, Tomoko Uchida <notifications@github.com>
wrote:

> Is there anything you would like to polish still?
>
> All obsolete and unused methods / parameters were removed.
> Thanks!
>
> In my environment (small data sets,) index optimization seems to work well.
> Could you share stack traces? I'll try to produce the failure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DmitryKey/luke/pull/27#issuecomment-116739960>.
>



-- 
Regards,

Dmitry Kan

**Comment by nathanaeljones** [comment]
Should I be getting an IndexFormatTooNewException when using Luke 5.2 with Lucene 5.3?

**Comment by mocobeta** [comment]
@nathanaeljones Yes, you should get IndexFormatTooNewException when using Luke 5.2 with Lucene 5.3. If you need Luke for Lucene 5.3, how about trying to check those pull requests?
#37 #38

**Pull request merged**
