### PR TITLE
Upgrade lucene version to 6.2.1

### PR DESCRIPTION
**Pull request by mocobeta**
Trivial update update for Lucene 6.2.1 release. #63 

It works well in my environment. Can we release Luke 6.2.1? :)

### CODE REVIEW

**Comment by DmitryKey** [comment]
@mocobeta it is a go from my side. Would you like to do the actual release? :)

**Comment by mocobeta** [comment]
@DmitryKey I'll try to make the release 👍

**Comment by DmitryKey** [comment]
@mocobeta 👍 let me know, if you need help!

**Comment by mocobeta** [comment]
@DmitryKey created the release 6.2.1. Could you check it?

**Comment by DmitryKey** [comment]
@mocobeta Thanks a lot for taking the release task! I'm about to test it against solr 6.2.1. But noticed, that About dialog box did not contain the proper version (if we find a way to propagate that from the code -- great). Fixed manually.
Also fixed a typo in the text. Would you like to re-spin the release?

**Comment by DmitryKey** [comment]
@mocobeta tested the release to functionally work against solr 6.2.1.

**Comment by mocobeta** [comment]
> But noticed, that About dialog box did not contain the proper version (if we find a way to propagate that from the code -- great). Fixed manually.
Missed it, thank you! I re-created the release 6.2.1 from current master ;-)

**Comment by DmitryKey** [comment]
excellent! Thanks, @mocobeta. Will you do the honors of broadcasting about the release? You could publish on solr-user and luke mailing list, if you'd like.

**Comment by mocobeta** [comment]
Sure, I'll announce the release solr-user and luke ML soon. Thanks!

**Comment by DmitryKey** [comment]
Thanks!

**Pull request merged**
