### PR TITLE
Issue #175: Offered improvement to reconstruction of unstored fields …

### PR DESCRIPTION
**Pull request by chris-bamford**
…with no position information

Replaces previous pull request attempt.
No conflicts here.

### CODE REVIEW

**Comment by chris-bamford** [comment]
Hi Dmitry,

With some help from a colleague we think we have done this correctly now.
I brought my local branch up to date with changes from luke-4.10.4-field-reconstruction and then added my changes and committed/pushed to my /luke-4.10.4-field-reconstruction-2 branch.  Hopefully the pull request is now OK for you.

Kind regards

- Chris

**Comment by DmitryKey** [comment]
Hi Chris,

Merged it now, thanks for your contribution! Will you be able to verify this on your data?

**Comment by chris-bamford** [comment]
Sorry, missed your response in the Christmas break!
I will now download the mani branch and verify it.

**Comment by chris-bamford** [comment]
I'll let you delete the fork as I am not 100% sure what I'm doing :-) . Please feel free.

**Comment by chris-bamford** [comment]
Hey @DmitryKey , what are the chances of this change making it's way into later versions of Luke (after 4.10.4)?

**Pull request merged**
