### PR TITLE
Upgrade lucene version to 6.0.0

### PR DESCRIPTION
**Pull request by mocobeta**
Those fixes are for Lucene 6.0.0 API changes.
- Changed APIs: NumericField (IntField is now LegacyIntField, and other NumericFields are also prefixed with 'Legacy')
- Removed APIs: DocsEnum, PayloadNearQuery, PayloadTermQuery, Query.setBoost()
- Deprecated APIs: IndexWriter.isLocked()

And, to support PointValues introduced at lucene 6.0.0, 
- Stop using SlowCompositeReaderWrapper (that cannot wrap LeafReaders that contains PointValues)
- Show PointValues (the dimension and num bytes per dimension)  in documents tab.

I have roughly tested those fixes with 'techproducts' example included with Solr 6.0.0. It can browse the index, optimize index, show docs, add new docs.
More tests may be needed, I need your help. Please try this branch :)

Thanks.

### CODE REVIEW

**Comment by DmitryKey** [comment]
thanks @mocobeta I'm going to test this soon.

**Comment by DmitryKey** [comment]
tested major functions, including search, index check and optimization. All work fine. This is ready for a release.

**Comment by mocobeta** [comment]
Thanks @DmitryKey ! I'll merge it to pivot branch soon.

**Comment by DmitryKey** [comment]
ok, thanks, @mocobeta !

**Pull request merged**
