### PR TITLE
Update Launching Luke section.

### PR DESCRIPTION
**Pull request by sriharshakappala**
I hope this instruction would be useful for the people who come from different programming community like Ruby/Python/Perl.

**Edit** I have also improved the existing launching luke section.

### CODE REVIEW

**Comment by DmitryKey** [comment]
hi @sriharshakappala Thanks for PR.
A quick question: How is what you mention in the Readme different from luke.sh and luke.bat? Have you tried running those?

**Comment by sriharshakappala** [comment]
@DmitryKey Firstly, thanks for your effort for updating luke to match the latest lucene versions! I was trying luke over the past week to analyze some of the indexes.

And yes, I tried running `./luke.sh` and luke didn't started, As a guy with little knowledge on Java, the prompts from `luke.sh` weren't of much help to me. It took a bit of research and time to get up and running with luke.

**Comment by DmitryKey** [comment]
@sriharshakappala you are welcome!

Could you pls paste the output or a screenshot of what you see when using luke.sh?

**Comment by sriharshakappala** [comment]
Sure thing! Here's the screenshot

screenshot from 2016-10-25 11-59-44

**Comment by DmitryKey** [comment]
@sriharshakappala thanks for the screenshot. I see now! It looks like you checked master of luke and trying to run it from the repo's root directory. The way this should be done, is: download the necessary version package from the releases page (https://github.com/DmitryKey/luke/releases), unzip it and run luke.sh. Hope this helps.

**Comment by sriharshakappala** [comment]
@DmitryKey Sounds good! Would you like to include the same as part of the README? I feel it would help others.

**Comment by DmitryKey** [comment]
Sure! Feel free to edit your PR and I'll gladly merge it :)

**Pull request merged**
